/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HARRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HARRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.HARLogEntry = factory(root.MegatonApi.ApiClient, root.MegatonApi.HARRequest);
  }
}(this, function(ApiClient, HARRequest) {
  'use strict';




  /**
   * The HARLogEntry model module.
   * @module model/HARLogEntry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HARLogEntry</code>.
   * @alias module:model/HARLogEntry
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>HARLogEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HARLogEntry} obj Optional instance to populate.
   * @return {module:model/HARLogEntry} The populated <code>HARLogEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('startedDateTime')) {
        obj['startedDateTime'] = ApiClient.convertToType(data['startedDateTime'], 'String');
      }
      if (data.hasOwnProperty('request')) {
        obj['request'] = HARRequest.constructFromObject(data['request']);
      }
    }
    return obj;
  }

  /**
   * @member {String} startedDateTime
   */
  exports.prototype['startedDateTime'] = undefined;
  /**
   * @member {module:model/HARRequest} request
   */
  exports.prototype['request'] = undefined;



  return exports;
}));


