/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HARPostData', 'model/NameValuePair'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HARPostData'), require('./NameValuePair'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.HARRequest = factory(root.MegatonApi.ApiClient, root.MegatonApi.HARPostData, root.MegatonApi.NameValuePair);
  }
}(this, function(ApiClient, HARPostData, NameValuePair) {
  'use strict';




  /**
   * The HARRequest model module.
   * @module model/HARRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HARRequest</code>.
   * @alias module:model/HARRequest
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>HARRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HARRequest} obj Optional instance to populate.
   * @return {module:model/HARRequest} The populated <code>HARRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('httpVersion')) {
        obj['httpVersion'] = ApiClient.convertToType(data['httpVersion'], 'String');
      }
      if (data.hasOwnProperty('cookies')) {
        obj['cookies'] = ApiClient.convertToType(data['cookies'], [NameValuePair]);
      }
      if (data.hasOwnProperty('headers')) {
        obj['headers'] = ApiClient.convertToType(data['headers'], [NameValuePair]);
      }
      if (data.hasOwnProperty('postData')) {
        obj['postData'] = HARPostData.constructFromObject(data['postData']);
      }
    }
    return obj;
  }

  /**
   * @member {String} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} httpVersion
   */
  exports.prototype['httpVersion'] = undefined;
  /**
   * @member {Array.<module:model/NameValuePair>} cookies
   */
  exports.prototype['cookies'] = undefined;
  /**
   * @member {Array.<module:model/NameValuePair>} headers
   */
  exports.prototype['headers'] = undefined;
  /**
   * @member {module:model/HARPostData} postData
   */
  exports.prototype['postData'] = undefined;



  return exports;
}));


