/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.HTTPResponse = factory(root.MegatonApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HTTPResponse model module.
   * @module model/HTTPResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HTTPResponse</code>.
   * @alias module:model/HTTPResponse
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>HTTPResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HTTPResponse} obj Optional instance to populate.
   * @return {module:model/HTTPResponse} The populated <code>HTTPResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('scriptEntryId')) {
        obj['scriptEntryId'] = ApiClient.convertToType(data['scriptEntryId'], 'Number');
      }
      if (data.hasOwnProperty('pointOfPresence')) {
        obj['pointOfPresence'] = ApiClient.convertToType(data['pointOfPresence'], 'String');
      }
      if (data.hasOwnProperty('vuId')) {
        obj['vuId'] = ApiClient.convertToType(data['vuId'], 'String');
      }
      if (data.hasOwnProperty('messageSize')) {
        obj['messageSize'] = ApiClient.convertToType(data['messageSize'], 'Number');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Number');
      }
      if (data.hasOwnProperty('receivedTimestamp')) {
        obj['receivedTimestamp'] = ApiClient.convertToType(data['receivedTimestamp'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} scriptEntryId
   */
  exports.prototype['scriptEntryId'] = undefined;
  /**
   * @member {String} pointOfPresence
   */
  exports.prototype['pointOfPresence'] = undefined;
  /**
   * @member {String} vuId
   */
  exports.prototype['vuId'] = undefined;
  /**
   * @member {Number} messageSize
   */
  exports.prototype['messageSize'] = undefined;
  /**
   * @member {String} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {Number} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} receivedTimestamp
   */
  exports.prototype['receivedTimestamp'] = undefined;



  return exports;
}));


