/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.LoadDistributionEntrySpec = factory(root.MegatonApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoadDistributionEntrySpec model module.
   * @module model/LoadDistributionEntrySpec
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LoadDistributionEntrySpec</code>.
   * @alias module:model/LoadDistributionEntrySpec
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>LoadDistributionEntrySpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoadDistributionEntrySpec} obj Optional instance to populate.
   * @return {module:model/LoadDistributionEntrySpec} The populated <code>LoadDistributionEntrySpec</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('useCaseId')) {
        obj['useCaseId'] = ApiClient.convertToType(data['useCaseId'], 'Number');
      }
      if (data.hasOwnProperty('pointOfPresence')) {
        obj['pointOfPresence'] = ApiClient.convertToType(data['pointOfPresence'], 'String');
      }
      if (data.hasOwnProperty('vuCount')) {
        obj['vuCount'] = ApiClient.convertToType(data['vuCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} useCaseId
   */
  exports.prototype['useCaseId'] = undefined;
  /**
   * @member {String} pointOfPresence
   */
  exports.prototype['pointOfPresence'] = undefined;
  /**
   * @member {Number} vuCount
   */
  exports.prototype['vuCount'] = undefined;



  return exports;
}));


