/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaselineExecution', 'model/BaselineExecutionSpec'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BaselineExecution'), require('../model/BaselineExecutionSpec'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.BaselineExecutionsApi = factory(root.MegatonApi.ApiClient, root.MegatonApi.BaselineExecution, root.MegatonApi.BaselineExecutionSpec);
  }
}(this, function(ApiClient, BaselineExecution, BaselineExecutionSpec) {
  'use strict';

  /**
   * BaselineExecutions service.
   * @module api/BaselineExecutionsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new BaselineExecutionsApi. 
   * @alias module:api/BaselineExecutionsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Execute baseline
     * Executes a baseline for a specified use-case
     * @param {Number} useCaseId 
     * @param {module:model/BaselineExecutionSpec} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BaselineExecution} and HTTP response
     */
    this.executeBaselineWithHttpInfo = function(useCaseId, body) {
      var postBody = body;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling executeBaseline");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling executeBaseline");
      }


      var pathParams = {
        'useCaseId': useCaseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = BaselineExecution;

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Execute baseline
     * Executes a baseline for a specified use-case
     * @param {Number} useCaseId 
     * @param {module:model/BaselineExecutionSpec} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BaselineExecution}
     */
    this.executeBaseline = function(useCaseId, body) {
      return this.executeBaselineWithHttpInfo(useCaseId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get baseline executions
     * Retrieve all executed baselines for a specified use-case
     * @param {Number} useCaseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/BaselineExecution>} and HTTP response
     */
    this.getBaselineExecutionsWithHttpInfo = function(useCaseId) {
      var postBody = null;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling getBaselineExecutions");
      }


      var pathParams = {
        'useCaseId': useCaseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [BaselineExecution];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get baseline executions
     * Retrieve all executed baselines for a specified use-case
     * @param {Number} useCaseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/BaselineExecution>}
     */
    this.getBaselineExecutions = function(useCaseId) {
      return this.getBaselineExecutionsWithHttpInfo(useCaseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
