/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HTTPMessageHeader', 'model/HTTPResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HTTPMessageHeader'), require('../model/HTTPResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.BaselineHTTPResponsesApi = factory(root.MegatonApi.ApiClient, root.MegatonApi.HTTPMessageHeader, root.MegatonApi.HTTPResponse);
  }
}(this, function(ApiClient, HTTPMessageHeader, HTTPResponse) {
  'use strict';

  /**
   * BaselineHTTPResponses service.
   * @module api/BaselineHTTPResponsesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new BaselineHTTPResponsesApi. 
   * @alias module:api/BaselineHTTPResponsesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get baseline response body
     * Retrieve body for a specified HTTP response and baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @param {Number} responseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.getBaselineHttpResponseBodyWithHttpInfo = function(useCaseId, executionId, responseId) {
      var postBody = null;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling getBaselineHttpResponseBody");
      }

      // verify the required parameter 'executionId' is set
      if (executionId === undefined || executionId === null) {
        throw new Error("Missing the required parameter 'executionId' when calling getBaselineHttpResponseBody");
      }

      // verify the required parameter 'responseId' is set
      if (responseId === undefined || responseId === null) {
        throw new Error("Missing the required parameter 'responseId' when calling getBaselineHttpResponseBody");
      }


      var pathParams = {
        'useCaseId': useCaseId,
        'executionId': executionId,
        'responseId': responseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions/{executionId}/http-responses/{responseId}/body', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get baseline response body
     * Retrieve body for a specified HTTP response and baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @param {Number} responseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.getBaselineHttpResponseBody = function(useCaseId, executionId, responseId) {
      return this.getBaselineHttpResponseBodyWithHttpInfo(useCaseId, executionId, responseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get baseline response headers
     * Retrieve headers for a specified HTTP response and baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @param {Number} responseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPMessageHeader>} and HTTP response
     */
    this.getBaselineHttpResponseHeadersWithHttpInfo = function(useCaseId, executionId, responseId) {
      var postBody = null;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling getBaselineHttpResponseHeaders");
      }

      // verify the required parameter 'executionId' is set
      if (executionId === undefined || executionId === null) {
        throw new Error("Missing the required parameter 'executionId' when calling getBaselineHttpResponseHeaders");
      }

      // verify the required parameter 'responseId' is set
      if (responseId === undefined || responseId === null) {
        throw new Error("Missing the required parameter 'responseId' when calling getBaselineHttpResponseHeaders");
      }


      var pathParams = {
        'useCaseId': useCaseId,
        'executionId': executionId,
        'responseId': responseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [HTTPMessageHeader];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions/{executionId}/http-responses/{responseId}/headers', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get baseline response headers
     * Retrieve headers for a specified HTTP response and baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @param {Number} responseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPMessageHeader>}
     */
    this.getBaselineHttpResponseHeaders = function(useCaseId, executionId, responseId) {
      return this.getBaselineHttpResponseHeadersWithHttpInfo(useCaseId, executionId, responseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get baseline responses
     * Retrieve HTTP responses for a specified baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPResponse>} and HTTP response
     */
    this.getBaselineHttpResponsesWithHttpInfo = function(useCaseId, executionId) {
      var postBody = null;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling getBaselineHttpResponses");
      }

      // verify the required parameter 'executionId' is set
      if (executionId === undefined || executionId === null) {
        throw new Error("Missing the required parameter 'executionId' when calling getBaselineHttpResponses");
      }


      var pathParams = {
        'useCaseId': useCaseId,
        'executionId': executionId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [HTTPResponse];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/baseline-executions/{executionId}/http-responses', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get baseline responses
     * Retrieve HTTP responses for a specified baseline exeuction
     * @param {Number} useCaseId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPResponse>}
     */
    this.getBaselineHttpResponses = function(useCaseId, executionId) {
      return this.getBaselineHttpResponsesWithHttpInfo(useCaseId, executionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
