/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HAR', 'model/HTTPScriptEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HAR'), require('../model/HTTPScriptEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.HARImportsApi = factory(root.MegatonApi.ApiClient, root.MegatonApi.HAR, root.MegatonApi.HTTPScriptEntry);
  }
}(this, function(ApiClient, HAR, HTTPScriptEntry) {
  'use strict';

  /**
   * HARImports service.
   * @module api/HARImportsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new HARImportsApi. 
   * @alias module:api/HARImportsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Import HAR
     * Sets the HTTP script for a use-case using an HTTP Archive
     * @param {Number} useCaseId 
     * @param {module:model/HAR} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPScriptEntry>} and HTTP response
     */
    this.importHarWithHttpInfo = function(useCaseId, body) {
      var postBody = body;

      // verify the required parameter 'useCaseId' is set
      if (useCaseId === undefined || useCaseId === null) {
        throw new Error("Missing the required parameter 'useCaseId' when calling importHar");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling importHar");
      }


      var pathParams = {
        'useCaseId': useCaseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [HTTPScriptEntry];

      return this.apiClient.callApi(
        '/v1/tenants/me/use-cases/{useCaseId}/har-imports', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Import HAR
     * Sets the HTTP script for a use-case using an HTTP Archive
     * @param {Number} useCaseId 
     * @param {module:model/HAR} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPScriptEntry>}
     */
    this.importHar = function(useCaseId, body) {
      return this.importHarWithHttpInfo(useCaseId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
