/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HTTPResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HTTPResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.MegatonApi) {
      root.MegatonApi = {};
    }
    root.MegatonApi.TestHTTPResponsesApi = factory(root.MegatonApi.ApiClient, root.MegatonApi.HTTPResponse);
  }
}(this, function(ApiClient, HTTPResponse) {
  'use strict';

  /**
   * TestHTTPResponses service.
   * @module api/TestHTTPResponsesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TestHTTPResponsesApi. 
   * @alias module:api/TestHTTPResponsesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get test responses
     * Retrieve HTTP responses for a specified test exeuction
     * @param {Number} testPlanId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HTTPResponse>} and HTTP response
     */
    this.getTestHttpResponsesWithHttpInfo = function(testPlanId, executionId) {
      var postBody = null;

      // verify the required parameter 'testPlanId' is set
      if (testPlanId === undefined || testPlanId === null) {
        throw new Error("Missing the required parameter 'testPlanId' when calling getTestHttpResponses");
      }

      // verify the required parameter 'executionId' is set
      if (executionId === undefined || executionId === null) {
        throw new Error("Missing the required parameter 'executionId' when calling getTestHttpResponses");
      }


      var pathParams = {
        'testPlanId': testPlanId,
        'executionId': executionId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['password'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [HTTPResponse];

      return this.apiClient.callApi(
        '/v1/tenants/me/test-plans/{testPlanId}/test-executions/{executionId}/http-responses', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get test responses
     * Retrieve HTTP responses for a specified test exeuction
     * @param {Number} testPlanId 
     * @param {Number} executionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HTTPResponse>}
     */
    this.getTestHttpResponses = function(testPlanId, executionId) {
      return this.getTestHttpResponsesWithHttpInfo(testPlanId, executionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
