/**
 * Megaton API
 * JSON API for the Megaton Cloud Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@megaton.cloud
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaselineExecution', 'model/BaselineExecutionSpec', 'model/HAR', 'model/HARLog', 'model/HARLogEntry', 'model/HARPostData', 'model/HARRequest', 'model/HTTPMessageHeader', 'model/HTTPResponse', 'model/HTTPScriptEntry', 'model/LoadDistributionEntry', 'model/LoadDistributionEntrySpec', 'model/NameValuePair', 'model/OAuthToken', 'model/Tenant', 'model/TenantSpec', 'model/TestExecution', 'model/TestPlan', 'model/TestPlanPatchOperation', 'model/TestPlanSpec', 'model/UseCase', 'model/UseCaseSpec', 'api/BaselineExecutionsApi', 'api/BaselineHTTPResponsesApi', 'api/HARImportsApi', 'api/HTTPScriptApi', 'api/LoadDistributionApi', 'api/OAuthTokensApi', 'api/TenantsApi', 'api/TestExecutionsApi', 'api/TestHTTPResponsesApi', 'api/TestPlansApi', 'api/UseCasesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/BaselineExecution'), require('./model/BaselineExecutionSpec'), require('./model/HAR'), require('./model/HARLog'), require('./model/HARLogEntry'), require('./model/HARPostData'), require('./model/HARRequest'), require('./model/HTTPMessageHeader'), require('./model/HTTPResponse'), require('./model/HTTPScriptEntry'), require('./model/LoadDistributionEntry'), require('./model/LoadDistributionEntrySpec'), require('./model/NameValuePair'), require('./model/OAuthToken'), require('./model/Tenant'), require('./model/TenantSpec'), require('./model/TestExecution'), require('./model/TestPlan'), require('./model/TestPlanPatchOperation'), require('./model/TestPlanSpec'), require('./model/UseCase'), require('./model/UseCaseSpec'), require('./api/BaselineExecutionsApi'), require('./api/BaselineHTTPResponsesApi'), require('./api/HARImportsApi'), require('./api/HTTPScriptApi'), require('./api/LoadDistributionApi'), require('./api/OAuthTokensApi'), require('./api/TenantsApi'), require('./api/TestExecutionsApi'), require('./api/TestHTTPResponsesApi'), require('./api/TestPlansApi'), require('./api/UseCasesApi'));
  }
}(function(ApiClient, BaselineExecution, BaselineExecutionSpec, HAR, HARLog, HARLogEntry, HARPostData, HARRequest, HTTPMessageHeader, HTTPResponse, HTTPScriptEntry, LoadDistributionEntry, LoadDistributionEntrySpec, NameValuePair, OAuthToken, Tenant, TenantSpec, TestExecution, TestPlan, TestPlanPatchOperation, TestPlanSpec, UseCase, UseCaseSpec, BaselineExecutionsApi, BaselineHTTPResponsesApi, HARImportsApi, HTTPScriptApi, LoadDistributionApi, OAuthTokensApi, TenantsApi, TestExecutionsApi, TestHTTPResponsesApi, TestPlansApi, UseCasesApi) {
  'use strict';

  /**
   * JSON_API_for_the_Megaton_Cloud_Platform.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var MegatonApi = require('index'); // See note below*.
   * var xxxSvc = new MegatonApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new MegatonApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new MegatonApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new MegatonApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BaselineExecution model constructor.
     * @property {module:model/BaselineExecution}
     */
    BaselineExecution: BaselineExecution,
    /**
     * The BaselineExecutionSpec model constructor.
     * @property {module:model/BaselineExecutionSpec}
     */
    BaselineExecutionSpec: BaselineExecutionSpec,
    /**
     * The HAR model constructor.
     * @property {module:model/HAR}
     */
    HAR: HAR,
    /**
     * The HARLog model constructor.
     * @property {module:model/HARLog}
     */
    HARLog: HARLog,
    /**
     * The HARLogEntry model constructor.
     * @property {module:model/HARLogEntry}
     */
    HARLogEntry: HARLogEntry,
    /**
     * The HARPostData model constructor.
     * @property {module:model/HARPostData}
     */
    HARPostData: HARPostData,
    /**
     * The HARRequest model constructor.
     * @property {module:model/HARRequest}
     */
    HARRequest: HARRequest,
    /**
     * The HTTPMessageHeader model constructor.
     * @property {module:model/HTTPMessageHeader}
     */
    HTTPMessageHeader: HTTPMessageHeader,
    /**
     * The HTTPResponse model constructor.
     * @property {module:model/HTTPResponse}
     */
    HTTPResponse: HTTPResponse,
    /**
     * The HTTPScriptEntry model constructor.
     * @property {module:model/HTTPScriptEntry}
     */
    HTTPScriptEntry: HTTPScriptEntry,
    /**
     * The LoadDistributionEntry model constructor.
     * @property {module:model/LoadDistributionEntry}
     */
    LoadDistributionEntry: LoadDistributionEntry,
    /**
     * The LoadDistributionEntrySpec model constructor.
     * @property {module:model/LoadDistributionEntrySpec}
     */
    LoadDistributionEntrySpec: LoadDistributionEntrySpec,
    /**
     * The NameValuePair model constructor.
     * @property {module:model/NameValuePair}
     */
    NameValuePair: NameValuePair,
    /**
     * The OAuthToken model constructor.
     * @property {module:model/OAuthToken}
     */
    OAuthToken: OAuthToken,
    /**
     * The Tenant model constructor.
     * @property {module:model/Tenant}
     */
    Tenant: Tenant,
    /**
     * The TenantSpec model constructor.
     * @property {module:model/TenantSpec}
     */
    TenantSpec: TenantSpec,
    /**
     * The TestExecution model constructor.
     * @property {module:model/TestExecution}
     */
    TestExecution: TestExecution,
    /**
     * The TestPlan model constructor.
     * @property {module:model/TestPlan}
     */
    TestPlan: TestPlan,
    /**
     * The TestPlanPatchOperation model constructor.
     * @property {module:model/TestPlanPatchOperation}
     */
    TestPlanPatchOperation: TestPlanPatchOperation,
    /**
     * The TestPlanSpec model constructor.
     * @property {module:model/TestPlanSpec}
     */
    TestPlanSpec: TestPlanSpec,
    /**
     * The UseCase model constructor.
     * @property {module:model/UseCase}
     */
    UseCase: UseCase,
    /**
     * The UseCaseSpec model constructor.
     * @property {module:model/UseCaseSpec}
     */
    UseCaseSpec: UseCaseSpec,
    /**
     * The BaselineExecutionsApi service constructor.
     * @property {module:api/BaselineExecutionsApi}
     */
    BaselineExecutionsApi: BaselineExecutionsApi,
    /**
     * The BaselineHTTPResponsesApi service constructor.
     * @property {module:api/BaselineHTTPResponsesApi}
     */
    BaselineHTTPResponsesApi: BaselineHTTPResponsesApi,
    /**
     * The HARImportsApi service constructor.
     * @property {module:api/HARImportsApi}
     */
    HARImportsApi: HARImportsApi,
    /**
     * The HTTPScriptApi service constructor.
     * @property {module:api/HTTPScriptApi}
     */
    HTTPScriptApi: HTTPScriptApi,
    /**
     * The LoadDistributionApi service constructor.
     * @property {module:api/LoadDistributionApi}
     */
    LoadDistributionApi: LoadDistributionApi,
    /**
     * The OAuthTokensApi service constructor.
     * @property {module:api/OAuthTokensApi}
     */
    OAuthTokensApi: OAuthTokensApi,
    /**
     * The TenantsApi service constructor.
     * @property {module:api/TenantsApi}
     */
    TenantsApi: TenantsApi,
    /**
     * The TestExecutionsApi service constructor.
     * @property {module:api/TestExecutionsApi}
     */
    TestExecutionsApi: TestExecutionsApi,
    /**
     * The TestHTTPResponsesApi service constructor.
     * @property {module:api/TestHTTPResponsesApi}
     */
    TestHTTPResponsesApi: TestHTTPResponsesApi,
    /**
     * The TestPlansApi service constructor.
     * @property {module:api/TestPlansApi}
     */
    TestPlansApi: TestPlansApi,
    /**
     * The UseCasesApi service constructor.
     * @property {module:api/UseCasesApi}
     */
    UseCasesApi: UseCasesApi
  };

  return exports;
}));
